# Generated by Django 2.2.5 on 2019-09-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0002_auto_20190928_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdata',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
