from .create_report_data import ReportDataCreateView
from .report_picture import ReportPictureView
from .report_data_list import ReportDataListView
from .report_selecting import ReportSelectingView
from .cleaner_picture import CleanerPictureView
from .user_create import UserCreateView
from .clean_finish import CleanFinishView
from .confirmation_data_list import CleanerDataListView
from .confirm_clean import ConfirmCleanView
from .cleaner_selecting import CleanerSelectingView
from .confirmation_picture import ConfirmationPictureView
